---
title: "QProMS Report"
subtitle: "Quantitative Proteomic Made Simple"
date: today
format:
  html:
    self-contained: true
    theme: flatly
    page-layout: article
    toc: true
    toc-location: left
    toc-depth: 3
    smooth-scroll: true
execute:
  echo: false
  warning: false
  message: false
params: 
  path: ""
  expdesign: ""
  valid_val_filter: ""
  valid_val_thr: ""
  pep_filter: ""
  pep_thr: ""
  rev: true
  cont: true
  oibs: true
  imputed_data: ""
---

```{r}
library(yaml)
library(tibble)
box::use(
  app/logic/R6Class_QProMS,
)

r6 <- R6Class_QProMS$QProMS$new()

r6$loading_data(input_path = params$path, input_type = "max_quant")

r6$expdesign <- as_tibble(params$expdesign)
r6$imputed_data <- as_tibble(params$imputed_data)

# r6$expdesign

r6$pg_preprocessing()

r6$data_wrangling(
        valid_val_filter = params$valid_val_filter,
        valid_val_thr = params$valid_val_thr,
        pep_filter = params$pep_filter,
        pep_thr = params$pep_thr,
        rev = params$rev,
        cont = params$cont,
        oibs = params$oibs
      )
```
# CIao
```{r}
r6$plot_protein_counts()
```

# ciao 2
```{r}
r6$plot_pca()
```

